"""Diagnostic plots — retailer gate and per-agent OSP.

Produces a single PNG `w8_diagnostics.png` with four panels:
  (a) OSP distribution per typology
  (b) OSP vs kWh sold per agent
  (c) Retailer assignment per typology
  (d) Per-agent V2G net cost, sorted

The plots are generated by instantiating fresh agents (the OSP and retailer
draws are deterministic from the agent seed) and replaying the same week
that `run_demo` uses.
"""

from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from src.agents.ev_agent import (
    EVAgent,
    ALL_TYPOLOGIES,
    DAILY_CHARGER,
    PUBLIC_CHARGER,
    BEV_2ND_VEHICLE,
    THRESHOLD_CHARGER,
    COUNTERFACTUAL_V2G,
    RETAILER_MARKET_SHARES,
)
from src.aggregator_stub import (
    AGGREGATOR_CONTRACTED_RETAILER,
    RETAILER_GATE_ENABLED,
)
from src.pricing import price_at_hour
from src.run_demo import CARS_PER_TYPOLOGY, HOURS_IN_WEEK


COLORS = {
    DAILY_CHARGER:     "#1f77b4",
    PUBLIC_CHARGER:    "#ff7f0e",
    BEV_2ND_VEHICLE:   "#2ca02c",
    THRESHOLD_CHARGER: "#d62728",
}

OUTPUTS_DIR = Path(__file__).resolve().parent.parent / "outputs"


def run_v2g_agents() -> list[dict]:
    """Instantiate and simulate every V2G agent in the fleet."""
    records = []
    for t_idx, typology in enumerate(ALL_TYPOLOGIES):
        n_cars = CARS_PER_TYPOLOGY[typology]
        for car_idx in range(n_cars):
            agent_id = t_idx * 1000 + car_idx + 1
            agent = EVAgent(
                agent_id=agent_id,
                typology=typology,
                counterfactual=COUNTERFACTUAL_V2G,
            )
            for hour in range(HOURS_IN_WEEK):
                hour_of_day = hour % 24
                day_of_week = (hour // 24) % 7
                price = price_at_hour(hour_of_day, day_of_week)
                agent.step(current_hour=hour, current_price_per_kwh=price)
            kwh_bought = sum(r["energy_kwh"] for r in agent.hourly_log if r["action"] == "CHARGE")
            kwh_sold = sum(-r["energy_kwh"] for r in agent.hourly_log if r["action"] == "DISCHARGE")
            net = sum(r["cost_currency"] for r in agent.hourly_log)
            records.append({
                "agent_id":   agent.id,
                "typology":   typology,
                "osp":        agent.state.osp,
                "intention":  agent.state.intention_to_use_v2g,
                "opted_in":   agent.state.v2g_opted_in,
                "retailer":   agent.state.retailer,
                "kwh_bought": kwh_bought,
                "kwh_sold":   kwh_sold,
                "net_week":   net,
            })
    return records


# -----------------------------------------------------------------------------
# Plot helpers
# -----------------------------------------------------------------------------

def panel_intention_histogram(ax, recs):
    """SEM Intention scores across the fleet, coloured by typology."""
    bins = np.arange(-2.0, 2.0, 0.20)
    for typology in ALL_TYPOLOGIES:
        vals = [r["intention"] for r in recs if r["typology"] == typology]
        ax.hist(vals, bins=bins, alpha=0.5, label=typology, color=COLORS[typology])
    ax.axvline(0.0, color="black", linestyle="--", linewidth=1, label="opt-in threshold")
    ax.set_xlabel("SEM Intention to Use V2G")
    ax.set_ylabel("count of agents")
    ax.set_title("(a) Intention distribution by typology")
    ax.legend(fontsize=8, loc="upper right")


def panel_intention_vs_sold(ax, recs):
    """Higher Intention should yield more kWh sold (lower OSP -> more discharge)."""
    for typology in ALL_TYPOLOGIES:
        if typology == PUBLIC_CHARGER:
            continue
        xs = [r["intention"] for r in recs if r["typology"] == typology]
        ys = [r["kwh_sold"] for r in recs if r["typology"] == typology]
        ax.scatter(xs, ys, color=COLORS[typology], label=typology, s=50, alpha=0.8)
    ax.axvline(0.0, color="black", linestyle="--", linewidth=1)
    ax.set_xlabel("SEM Intention to Use V2G")
    ax.set_ylabel("kWh sold during the week")
    ax.set_title("(b) Intention vs energy discharged per agent")
    ax.legend(fontsize=8, loc="upper right")


def panel_retailer_stack(ax, recs):
    # Count retailers per typology
    retailers = list(RETAILER_MARKET_SHARES.keys())
    typology_retailer_counts = {t: defaultdict(int) for t in ALL_TYPOLOGIES}
    for r in recs:
        typology_retailer_counts[r["typology"]][r["retailer"]] += 1

    x = np.arange(len(ALL_TYPOLOGIES))
    bottom = np.zeros(len(ALL_TYPOLOGIES))
    cmap = plt.colormaps.get_cmap("tab20")
    for i, retailer in enumerate(retailers):
        heights = [typology_retailer_counts[t].get(retailer, 0) for t in ALL_TYPOLOGIES]
        color = "#28a745" if retailer == AGGREGATOR_CONTRACTED_RETAILER else cmap(i / len(retailers))
        ax.bar(x, heights, bottom=bottom, label=retailer, color=color)
        bottom = bottom + np.array(heights)
    ax.set_xticks(x)
    ax.set_xticklabels([t.replace(" ", "\n") for t in ALL_TYPOLOGIES], fontsize=8)
    ax.set_ylabel("count of agents")
    title = "(c) Retailer per typology"
    if RETAILER_GATE_ENABLED:
        title += f"  (green = {AGGREGATOR_CONTRACTED_RETAILER}, eligible for V2G)"
    ax.set_title(title)
    ax.legend(fontsize=7, loc="upper right", ncol=2)


def panel_per_agent_earnings(ax, recs):
    sorted_recs = sorted(recs, key=lambda r: r["net_week"])
    xs = np.arange(len(sorted_recs))
    colors = [COLORS[r["typology"]] for r in sorted_recs]
    heights = [r["net_week"] for r in sorted_recs]
    bars = ax.bar(xs, heights, color=colors)
    ax.axhline(0, color="black", linewidth=0.5)
    ax.set_xticks(xs)
    ax.set_xticklabels(
        [f"{r['typology'].split()[0][:3]}#{r['agent_id']}" for r in sorted_recs],
        rotation=45, fontsize=7, ha="right",
    )
    ax.set_ylabel("Weekly net cost (NIS)")
    ax.set_title("(d) Per-agent V2G net cost, sorted (negative = earned)")
    # Legend
    from matplotlib.patches import Patch
    handles = [Patch(facecolor=COLORS[t], label=t) for t in ALL_TYPOLOGIES]
    ax.legend(handles=handles, fontsize=7, loc="upper left")


def main() -> None:
    print("Running 20-car V2G fleet simulation for diagnostics...")
    recs = run_v2g_agents()

    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    panel_intention_histogram(axes[0][0], recs)
    panel_intention_vs_sold(axes[0][1], recs)
    panel_retailer_stack(axes[1][0], recs)
    panel_per_agent_earnings(axes[1][1], recs)

    gate_state = "ON" if RETAILER_GATE_ENABLED else "OFF"
    fig.suptitle(
        f"Diagnostics  -  retailer gate {gate_state}, aggregator contracted with {AGGREGATOR_CONTRACTED_RETAILER}",
        fontsize=13, fontweight="bold",
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))

    out = OUTPUTS_DIR / "w8_diagnostics.png"
    fig.savefig(out, dpi=150)
    print(f"Saved {out}")

    # Also print a small summary table to stdout
    print()
    print(f"{'agent':>16} | {'intent':>6} | {'opt_in':>6} | {'OSP':>5} | {'retailer':>14} | {'kWh sold':>9} | {'net NIS/wk':>11}")
    print("-" * 95)
    for r in sorted(recs, key=lambda r: (r["typology"], r["agent_id"])):
        print(
            f"{r['typology'][:8] + ' #' + str(r['agent_id']):>16} | "
            f"{r['intention']:>6.2f} | "
            f"{str(r['opted_in']):>6} | "
            f"{r['osp']:>5.2f} | "
            f"{r['retailer']:>14} | "
            f"{r['kwh_sold']:>9.1f} | "
            f"{r['net_week']:>11.2f}"
        )


if __name__ == "__main__":
    main()
